name: linux-x86_64

on:
  pull_request:
  push:
    branches:
      - main
      - feature-*
      - test-*
      - fix-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3

      - name: Compile and Test
        run: |
          sudo apt update && sudo apt install libffi-dev pkg-config
          mix deps.get
          export CFLAGS="-fsanitize=address -g"
          export CMD="$(ELIXIR_CLI_DRY_RUN=1 mix)"
          export CMD_ARGS="${CMD:3}"
          export ERL="$(which erl)"
          export ERL_BASE="$(dirname $(dirname ${ERL}))"
          export ELREXEC="$(find "${ERL_BASE}" -name erlexec)"
          export BINDIR="$(dirname ${ELREXEC})"
          export START_BOOT="$(find $ERL_BASE -name start.boot | grep -v release)"
          export ROOTDIR="$(dirname $(dirname ${START_BOOT}))"
          export EMU=beam
          bash -c "$ELREXEC $CMD_ARGS test" || true
          bash -c "LD_PRELOAD=$(gcc -print-file-name=libasan.so) $ELREXEC $CMD_ARGS test" || true
          mix test --max-cases 1
          mix coveralls.github
