name: linux-x86_64

on:
  pull_request:
  push:
    branches:
      - main
      - feature-*
      - test-*
      - fix-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - '.github/workflows/nerves-*'
      - '.github/workflows/macos-*'
  workflow_dispatch:

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24.2
          elixir-version: 1.13.3

      - name: Compile and Test
        run: |
          sudo apt update && sudo apt install libffi-dev pkg-config
          mix deps.get
          mix test --max-cases 1
