name: macos-x86_64

on:
  pull_request:
  push:
    branches:
      - main
      - test-*
    paths-ignore:
      - '**/README.md'
      - 'examples/**'
      - '.github/workflows/nerves-*'
      - '.github/workflows/linux-*.yml'
      - '.github/workflows/test-*.yml'
  workflow_dispatch:

concurrency:
  group: build-and-test-mac-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mix_test:
    runs-on: macos-11
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Erlang and Elixir
        run: |
          brew install erlang
          brew install elixir
          brew install libffi pkg-config
          mix local.hex --force
          mix local.rebar --force

      - name: Compile and Test
        run: |
          mix deps.get
          mix test
          bash ci/repeat-run-mix-test.sh
